# Generated by Django 3.2.12 on 2022-03-31 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price', models.FloatField(verbose_name='Bid Price')),
                ('bid_datetime', models.DateTimeField(verbose_name='Bid Time')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.order')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userinfo.supplier')),
            ],
        ),
    ]
