# Generated by Django 3.2.12 on 2022-03-31 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='Engineer Username')),
                ('password', models.CharField(max_length=64, verbose_name='password')),
                ('email', models.EmailField(max_length=64, verbose_name='TI email')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='Supplier Username')),
                ('password', models.CharField(max_length=64, verbose_name='password')),
                ('email', models.EmailField(max_length=64, verbose_name='Company email')),
            ],
        ),
    ]
