# Generated by Django 3.2.12 on 2022-04-13 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=32)),
                ('order_amount', models.IntegerField()),
                ('order_date', models.DateField()),
                ('order_status', models.IntegerField()),
                ('order_file', models.CharField(max_length=128)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userinfo.engineer')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='userinfo.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=32)),
                ('template_json', models.JSONField(max_length=64)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userinfo.engineer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userinfo.supplier')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.template'),
        ),
    ]
